name: Deploy docs to github pages

# This is more reasonable but will break
# arcanely if the pull request comes from a fork

#on:
#  pull_request:
#    types:
#      - closed
#    branches:
#      - main

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Again, making it run only on merged PRs is
    # more sane,
    # but it will break in unfathomable ways if the
    # PR comes from a fork.
    #if: github.event.pull_request.merged == true

    # this is needed!!
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    env:
      # Enable debug logging for `gh` command
      GH_DEBUG: api
      # Give `gh` command access to repo
      GH_TOKEN: ${{ github.token }}
      # These should be defined automatically,
      # but just to make sure.
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_SHA: ${{ github.sha }}

    # These shouldn't be inherrited from global scope,
    # but sometimes they are.
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        run: |
          # echo to stderr
          eecho() {
                  echo "$@" >&2
          }

          # echo to stderr and exit with error
          die() {
                  eecho "$@"
                  exit 1
          }

          test "$GITHUB_REPOSITORY" || \
            die 'GITHUB_REPOSITORY missing!'
          test "$GITHUB_SHA" || die 'GITHUB_SHA missing!'
          test "$GH_TOKEN" || die 'GH_TOKEN missing!'
          test "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" || \
            die 'ACTIONS_ID_TOKEN_REQUEST_TOKEN missing!!'
          test "$ACTIONS_ID_TOKEN_REQUEST_URL" || \
            die 'ACTIONS_ID_TOKEN_REQUEST_URL missing!!'

          repo="$GITHUB_REPOSITORY"

          echo "repo: $repo"

          echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN length: "
          echo -n "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" | wc -c

          echo "ACTIONS_ID_TOKEN_REQUEST_URL: "
          echo "$ACTIONS_ID_TOKEN_REQUEST_URL"

          #gh api "repos/$repo/actions/runs" > \
          #	archive/gh-api-sample-repos-actions-runs.json
          #


          run_id="$(gh api "repos/$repo/actions/runs" --jq \ '
                  .workflow_runs |
                  map(select(
                          .path == ".github/workflows/on-pull-request.yml"
                          and
                          .conclusion == "success"
                          )) |
                  sort_by(.head_commit.timestamp)
                          .[-1]
                          .id
                  ' 
                  )" || die "Failed to get last run ID"

          test "$run_id" || die "Failed to get last run ID"

          echo "Run ID: $run_id"

          #gh api "repos/$repo/actions/runs/$run_id/artifacts" > \
          #	archive/gh-api-sample-repos-actions-runs-artifacts.json

          artifact_id="$(gh api "repos/$repo/actions/runs/$run_id/artifacts" --jq '
                  .artifacts |
                  map(select(
                          .name == "github-pages"
                          ))
                  .[0]
                  .id
                  '
                  )" || die "Failed to get artifact id"

          test "$artifact_id" || die "Failed to get artifact id"

          echo "Artifact ID: $artifact_id"

          # This causes some WEIRD issues!
          # Better to do it manually i think
          #
          #echo "Attempt enabling pages..."
          #gh api \
          #  --method POST \
          #  "/repos/$repo/pages" \
          #  -f 'build_type=workflow' \
          #  || echo "It failed but that's probably OK"

          oidc_token="$(
            curl -sSL \
              -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
              "$ACTIONS_ID_TOKEN_REQUEST_URL" | \
            jq -r '.value'
            )" || die "Failed to get OIDC token"

          test "$oidc_token" || die "Failed to get OIDC token"

          echo "OIDC token length: $(echo -n "$oidc_token" | wc -c)"

          # error 404 -> pages not enabled thru actions
          # error 500 with " unexpected end of JSON input"
          #   -> using github token instead of OIDC token

          gh api \
                  --method POST \
                  /repos/$repo/pages/deployments \
                  --field "artifact_id=$artifact_id" \
                  -f 'environment=github-pages' \
                  -f pages_build_version="$GITHUB_SHA" \
                  -f oidc_token="$oidc_token" \
                  || die "Failed to deploy pages."




